# This file is part of ansible-openvpn-client.
# Copyright (C) 2015 Leo Gaspard
#
# ansible-openvpn-client is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ansible-openvpn-client is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ansible-openvpn-client.  If not, see <http://www.gnu.org/licenses/>.
---

- changed_when: false
  delegate_to: "{{ openvpn_client_server }}"
  block:
   - name: "read ca cert"
     command: "/bin/cat {{openvpn_client_server_home}}/pki/ca.crt"
     register: ca_crt

   - name: "read client keys"
     command: "/bin/cat {{openvpn_client_server_home}}/pki/{{inventory_hostname}}.crt"
     register: client_crt

   - name: "read client private keys"
     command: "/bin/cat {{openvpn_client_server_home}}/pki/private/{{inventory_hostname}}.key"
     register: client_priv

   - name: "read trust anchor"
     command: "/bin/cat {{openvpn_client_server_home}}/pki/private/ta.key"
     register: ta_priv

- name: "generate configuration file"
  template:
    src: "client.ovpn.j2"
    dest: "{{openvpn_client_home}}/config.ovpn"
    owner: root
    group: root
    mode: 0700
